---

- name: Install System Packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  sudo: yes
  with_items:
    - build-essential
    - python-dev
    - python-pip
    - libpq-dev
    - python-pip
    - git
    - binutils
    - libproj-dev
    - gdal-bin
    - python-matplotlib
    - libpng-dev

- name: Clone Pyramid Repository
  git: repo=https://github.com/meslater1030/calcutor.git dest={{ home }} force=yes

- name: Install Python Dependencies
  sudo: yes
  pip:
    state: present
    requirements: "{{ calcutor_home }}/requirements.txt"

- name: Develop App
  sudo: yes
  shell: python setup.py develop
  args:
    chdir: "{{ calcutor_home }}"