language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5.0b3"
  - "3.5-dev"
  - "nightly"
# command to install dependencies
install:
    - "pip install -r requirements.txt"
    - "pip install matplotlib"
# command to run tests
script: nosetests

notifications:
    email: false

addons:
  firefox: "37.0.1"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
env:
  matrix:
    - TESTENV=linters
    - TESTENV=py27
    - TESTENV=py27-xdist
    - TESTENV=py27-pytest-latest
    - TESTENV=py34
    - TESTENV=coveralls
script: tox -e $TESTENV
branches:
  except:
    - /^\d/