---

- name: Install Requirements
  sudo: yes
  pip: name=gunicorn state=present

- name: Create gunicorn Upstart Job
  sudo: yes
  template: src=calcutor.conf.j2 dest=/etc/init/calcutor.conf

- name: Start gunicorn Upstart Job
  sudo: yes
  service: name=calcutor state=restarted

